.TH "cache_key_hash_function" 3 "Sun Oct 6 2019" "xm_assessment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_key_hash_function \- The \fBcache_key_hash_function\fP struct Hash function for default cache Key type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cache\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T1 , class T2 > std::size_t \fBoperator()\fP (const std::pair< T1, T2 > &t) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBcache_key_hash_function\fP struct Hash function for default cache Key type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for xm_assessment from the source code\&.
